#!/bin/ksh
#
# Adds a user to yp group
# ypadduser username group
#

. ./ypconf

groupline="$(grep -n ${2}: ${YPFILES}/group | cut -d':' -f1)"

sed "${groupline}s/$/,${1}/" "${YPFILES}"/group > "${YPFILES}"/group.tmp
mv "${YPFILES}"/group.tmp "${YPFILES}"/group

ypmake
