#!/bin/ksh
#
# Sets up /etc/shells with default shells and nissh and creates nissh symlink
# (Default shells are from Solaris 10)
#

. $(dirname "$0")/ypconf

cat << EOF > /etc/shells
/bin/bash
/bin/csh
/bin/jsh
/bin/ksh
/bin/pfcsh
/bin/pfksh
/bin/pfsh
/bin/sh
/bin/tcsh
/bin/zsh
/bin/nissh
/sbin/jsh
/sbin/sh
/usr/bin/bash
/usr/bin/csh
/usr/bin/jsh
/usr/bin/ksh
/usr/bin/pfcsh
/usr/bin/pfksh
/usr/bin/pfsh
/usr/bin/sh
/usr/bin/tcsh
/usr/bin/zsh
EOF

ln -s "${NISSH}" /bin/nissh
